# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'androidBoy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/pngs/android_boy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabMain = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMain.sizePolicy().hasHeightForWidth())
        self.tabMain.setSizePolicy(sizePolicy)
        self.tabMain.setMinimumSize(QtCore.QSize(0, 0))
        self.tabMain.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabMain.setBaseSize(QtCore.QSize(0, 0))
        self.tabMain.setAcceptDrops(True)
        self.tabMain.setAutoFillBackground(False)
        self.tabMain.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabMain.setTabsClosable(False)
        self.tabMain.setObjectName("tabMain")
        self.gridLayout_2.addWidget(self.tabMain, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 0, 1, 1)
        self.TestButtonsLayout = QtWidgets.QHBoxLayout()
        self.TestButtonsLayout.setObjectName("TestButtonsLayout")
        self.btTestMemory = QtWidgets.QPushButton(Form)
        self.btTestMemory.setObjectName("btTestMemory")
        self.TestButtonsLayout.addWidget(self.btTestMemory)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TestButtonsLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.TestButtonsLayout, 0, 0, 1, 1)
        self.lbStatus = QtWidgets.QLabel(Form)
        self.lbStatus.setObjectName("lbStatus")
        self.gridLayout.addWidget(self.lbStatus, 6, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabMain.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AndroidBoy"))
        self.btTestMemory.setText(_translate("Form", "testMemory"))
        self.lbStatus.setText(_translate("Form", "TextLabel"))
import AndroidBoy_rc
