# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogTraceDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(397, 536)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/pngs/android_boy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbMessage = QtWidgets.QTextEdit(Dialog)
        self.tbMessage.setReadOnly(True)
        self.tbMessage.setObjectName("tbMessage")
        self.verticalLayout.addWidget(self.tbMessage)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbMappingPath = QtWidgets.QLineEdit(Dialog)
        self.tbMappingPath.setObjectName("tbMappingPath")
        self.horizontalLayout_2.addWidget(self.tbMappingPath)
        self.btMappingPath = QtWidgets.QPushButton(Dialog)
        self.btMappingPath.setObjectName("btMappingPath")
        self.horizontalLayout_2.addWidget(self.btMappingPath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btOK = QtWidgets.QPushButton(Dialog)
        self.btOK.setMinimumSize(QtCore.QSize(0, 30))
        self.btOK.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btOK.setObjectName("btOK")
        self.horizontalLayout.addWidget(self.btOK)
        self.btCopy = QtWidgets.QPushButton(Dialog)
        self.btCopy.setMinimumSize(QtCore.QSize(0, 30))
        self.btCopy.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btCopy.setObjectName("btCopy")
        self.horizontalLayout.addWidget(self.btCopy)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Trace detail"))
        self.btMappingPath.setText(_translate("Dialog", "Browser"))
        self.btOK.setText(_translate("Dialog", "OK"))
        self.btCopy.setText(_translate("Dialog", "Copy"))
import AndroidBoy_rc
