# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jsonFormatView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(773, 626)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sourceTxt = QtWidgets.QPlainTextEdit(Form)
        self.sourceTxt.setObjectName("sourceTxt")
        self.horizontalLayout.addWidget(self.sourceTxt)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rbJson = QtWidgets.QRadioButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbJson.sizePolicy().hasHeightForWidth())
        self.rbJson.setSizePolicy(sizePolicy)
        self.rbJson.setMinimumSize(QtCore.QSize(0, 30))
        self.rbJson.setObjectName("rbJson")
        self.verticalLayout_2.addWidget(self.rbJson)
        self.rbXml = QtWidgets.QRadioButton(Form)
        self.rbXml.setMinimumSize(QtCore.QSize(0, 30))
        self.rbXml.setObjectName("rbXml")
        self.verticalLayout_2.addWidget(self.rbXml)
        self.rbBase64 = QtWidgets.QRadioButton(Form)
        self.rbBase64.setMinimumSize(QtCore.QSize(0, 30))
        self.rbBase64.setObjectName("rbBase64")
        self.verticalLayout_2.addWidget(self.rbBase64)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(15, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.resultTxt = QtWidgets.QPlainTextEdit(Form)
        self.resultTxt.setObjectName("resultTxt")
        self.horizontalLayout.addWidget(self.resultTxt)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.rbJson.setText(_translate("Form", "JSON"))
        self.rbXml.setText(_translate("Form", "XML"))
        self.rbBase64.setText(_translate("Form", "Base64"))
        self.pushButton.setText(_translate("Form", ">"))
