# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewCCTGManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(602, 529)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self._treeTasks = QtWidgets.QTreeWidget(Form)
        self._treeTasks.setObjectName("_treeTasks")
        self._treeTasks.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self._treeTasks)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._btStart = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btStart.sizePolicy().hasHeightForWidth())
        self._btStart.setSizePolicy(sizePolicy)
        self._btStart.setMinimumSize(QtCore.QSize(28, 24))
        self._btStart.setMaximumSize(QtCore.QSize(28, 24))
        self._btStart.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/bt_start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btStart.setIcon(icon)
        self._btStart.setObjectName("_btStart")
        self.horizontalLayout.addWidget(self._btStart)
        self._btStop = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btStop.sizePolicy().hasHeightForWidth())
        self._btStop.setSizePolicy(sizePolicy)
        self._btStop.setMinimumSize(QtCore.QSize(28, 24))
        self._btStop.setMaximumSize(QtCore.QSize(28, 24))
        self._btStop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/bt_stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btStop.setIcon(icon1)
        self._btStop.setIconSize(QtCore.QSize(16, 16))
        self._btStop.setObjectName("_btStop")
        self.horizontalLayout.addWidget(self._btStop)
        self._btClear = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btClear.sizePolicy().hasHeightForWidth())
        self._btClear.setSizePolicy(sizePolicy)
        self._btClear.setMinimumSize(QtCore.QSize(28, 24))
        self._btClear.setMaximumSize(QtCore.QSize(28, 24))
        self._btClear.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/bt_clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btClear.setIcon(icon2)
        self._btClear.setObjectName("_btClear")
        self.horizontalLayout.addWidget(self._btClear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self._btStop.setToolTip(_translate("Form", "Stop"))
import AndroidBoy_rc
